### ISSUE TITLE
Chapter 2 - Board Games JSON Format Question

### ISSUE THREAD

**Issue by drdexter33** [Darkseal/ASP.NET-Core-Web-API#4]
At the end of Chapter 2 the book is showing the API result from the https://localhost:55221/boardgames endpoint as being formatted:

![image](https://github.com/Darkseal/ASP.NET-Core-Web-API/assets/15314276/0a6f0401-5e63-4fac-90a2-070beb585b94)

My results are not formatted in my web browser:

![image](https://github.com/Darkseal/ASP.NET-Core-Web-API/assets/15314276/cb4f4960-21d4-4d7d-b7d9-2f051b9ff8ec)

Should they be?

If I run this in Postman and select Pretty Print, it's formatting correctly:

![image](https://github.com/Darkseal/ASP.NET-Core-Web-API/assets/15314276/e49cacb7-54f1-44a0-a9f5-281a35f18ca8)

thanks.

**Comment by Darkseal** [comment]
Hello there,

first of all: thanks a lot for purchasing my book :)

Regarding your question, the JSON formatting/indentation depends on the browser you use (some apply indentation & pretty print by default, some don't) and/or how you have configured the Json default settings in your `Program.cs` file.

For example, this is how you can activate indentation for all JSON outputs:

```
builder.Services.AddControllers()
            .AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.WriteIndented = true;
            });
```

For additional info, check out [this page](https://learn.microsoft.com/it-it/dotnet/api/system.text.json.jsonserializeroptions?view=net-8.0).

**Comment by drdexter33** [comment]
Perfect!

![image](https://github.com/Darkseal/ASP.NET-Core-Web-API/assets/15314276/2807f78a-eb99-4127-ae27-7a737acf2b2e)

thanks!
