### ISSUE TITLE
Front End Question

### ISSUE THREAD

**Issue by drdexter33** [Darkseal/ASP.NET-Core-Web-API#7]
If I'm not incorrect, It seems that this book is specifically for writing the back-end API for a web application.

Can you recommend a technology/book to add the front end to the app?

Thanks..

**Comment by Darkseal** [comment]
Hello Dexter,

first of all, thank you for purchasing my book!

As for your question, there are a lot of good programming books about front-end and back-end interaction that I would like to recommend, including the series "ASP.NET Core and Angular" (also written by me), available here:

https://www.amazon.com/ASP-NET-Core-Angular-Full-stack-development/dp/1803239700/

I wrote this book together with "Building Web APIs with ASP.NET Core", and using the same framework version (.NET 6): however, we're just releasing the next edition (with .NET 8 and Angular 17), which should be available in the next few weeks.

Other than my Angular book series, here are some other useful resources that I could recommend for using ASP.NET Core + React.JS:

- https://www.udemy.com/course/building-applications-with-react-and-aspnet-core/ (good video course)
- https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-8.0&tabs=visual-studio (great tutorials)
