### ISSUE TITLE
Create a single Board Game Question

### ISSUE THREAD

**Issue by drdexter33** [Darkseal/ASP.NET-Core-Web-API#8]
Is there a way outside of the seed functionality to create say a single new board game?

thanks

**Comment by Darkseal** [comment]
No, there isn't an endpoint for that in the sample API provided by the book. However, you can easily modify the existing `Post()` method of the `BoardGamesController` to achieve such a result:

        public async Task<RestDTO<BoardGame?>> Post(BoardGameDTO model)
        {
            var boardgame = await _context.BoardGames
                .Where(b => b.Id == model.Id)
                .FirstOrDefaultAsync();
            if (boardgame != null)
            {
                if (!string.IsNullOrEmpty(model.Name))
                    boardgame.Name = model.Name;
                if (model.Year.HasValue && model.Year.Value > 0)
                    boardgame.Year = model.Year.Value;
                boardgame.LastModifiedDate = DateTime.Now;
                _context.BoardGames.Update(boardgame);
                await _context.SaveChangesAsync();
            }
            else {
                // TODO: create a new boardgame entity here
            }
      }

Set a value of `0` or `-1` in the `model.Id` property of the new boardgame to ensure it won't be found in the DBMS, thus forcing the `else` condition to occur.

The code to create a new BoardGame entity can be taken from the `SeedController`.
